### ISSUE TITLE
Can't compile libglvnd with meson : AttributeError: 'TernaryNode' object has no attribute 'subdir'

### ISSUE THREAD

**Issue by kentosama** [NVIDIA/libglvnd#198]
Hello, it's not possible to build the library with meson. I'm trying to build a backports package for Debian Buster and I must use meson for backporting from Debian sid. Can you fix it ? Thanks by advance.

```
kentosama@backports:~/source/libglvnd$ meson buildir
The Meson build system
Version: 0.49.2
Source dir: /home/kentosama/source/libglvnd
Build dir: /home/kentosama/source/libglvnd/buildir
Build type: native build
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 112, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 230, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 178, in _generate
    intr = interpreter.Interpreter(b)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 1918, in __init__
    self.load_root_meson_file()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 380, in load_root_meson_file
    self.ast = mparser.Parser(code, self.subdir).parse()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 500, in parse
    block = self.codeblock()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 778, in codeblock
    curline = self.line()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 761, in line
    block = self.ifblock()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 738, in ifblock
    block = self.codeblock()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 778, in codeblock
    curline = self.line()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 761, in line
    block = self.ifblock()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 740, in ifblock
    self.elseifblock(clause)
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 748, in elseifblock
    b = self.codeblock()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 778, in codeblock
    curline = self.line()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 772, in line
    return self.statement()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 505, in statement
    return self.e1()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 515, in e1
    value = self.e1()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 508, in e1
    left = self.e2()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 533, in e2
    left = self.e3()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 542, in e3
    left = self.e4()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 551, in e4
    left = self.e5()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 560, in e5
    return self.e5add()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 563, in e5add
    left = self.e5sub()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 569, in e5sub
    left = self.e5mod()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 575, in e5mod
    left = self.e5mul()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 581, in e5mul
    left = self.e5div()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 587, in e5div
    left = self.e6()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 597, in e6
    return self.e7()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 614, in e7
    left = self.method_call(left)
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 706, in method_call
    args = self.args()
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 678, in args
    a = ArgumentNode(s)
  File "/usr/lib/python3/dist-packages/mesonbuild/mparser.py", line 405, in __init__
    self.subdir = token.subdir
AttributeError: 'TernaryNode' object has no attribute 'subdir'

```

**Comment by kentosama** [comment]
I was able to build the library from the latest meson.

**Comment by rzr** [comment]
I also faced this on meson-0.49.2-1

**Comment by rzr** [comment]
For the record it is merged upstream at:

https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/230#

as suggested by @kbrenneman
